### ISSUE TITLE
Error using cplexlink1270 (null)

### ISSUE THREAD

**Issue by toseattle** [zijunwei/Region-Ranking-SVM#1]
Hi there, 

I got an error when I ran demo_S.m,  the detailed information is listed as follows. I am using matlab 2016a, vs 2013, cplex 12.7 on Win 10. Both 'createTestData.m' and 'RRSVM_s.m' work well, the error only occurred when I ran 'demo_S.m'. The built-in examples with Cplex work well. Any suggestions would be appreciated!

Getting QCs 300/300 (100.00%)
Error using cplexlink1270
(null)

Error in Cplex/solve

Error in Cplex/subsref

Error in RRSVM_s.update_sb (line 205)
            cplex.solve();

Error in RRSVM_s.train (line 71)
                [s, b, objVal] = RRSVM_s.update_sb(IS, lb, Q4S, ub4sumQC);

Error in demo_S (line 48)
[w, b, s, objVals] = RRSVM_s.train(trD, trLb, lambda, opts);
 
>>

**Comment by toseattle** [comment]
The cplex built-in examples work well.

**Comment by zijunwei** [comment]
Hi, I'm currently out of office without a working computer.
Possible reasons I can think of:
1. change all the data format to single 
2. try version 12.5
3. try some other quadratic programming solvers

If still not working, let me know

**Comment by toseattle** [comment]
Zijun, cplex 12.5 version can work. Thanks.

**Comment by zijunwei** [comment]
good to know. Thanks
